name: cncmachinecalculations
description: "A new Flutter project."
publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # File Handling & Storage
  file_picker: ^9.0.2
  excel: ^4.0.6
  path_provider: ^2.1.2
  open_file: ^3.5.10
  sqflite: ^2.3.2

  # UI & Notifications
  fluttertoast: ^8.2.4
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Uncomment to add assets (images, files, etc.)
  # assets:
  #   - assets/images/
  #   - assets/excel_templates/

  # Uncomment to add custom fonts
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
  #       - asset: assets/fonts/CustomFont-Bold.ttf
  #         weight: 700
